site_name: PDC
theme: 
  name: material
  font:
    text: 'Roboto'
    code: 'Fira Code'
extra_css:
  - static/css/styles.css
extra_javascript:
  - static/js/custom.js
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - attr_list
nav:
  - Home: index.md
