site_name: PDC
theme: 
  name: material
  font:
    text: 'Roboto'
    code: 'Fira Code'
extra_css:
  - static/css/styles.css
extra_javascript:
  - static/js/custom.js
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - attr_list
nav:
  - Home: index.md
  - Abinit: abinit/index.md
  - Cosma: cosma/index.md
  - Cp2k: cp2k/index.md
  - Cubelib: cubelib/index.md
  - Elk: elk/index.md
  - Elpa: elpa/index.md
  - Fenics: fenics/index.md
  - Fleur: fleur/index.md
  - Gamess: gamess/index.md
  - Gromacs: gromacs/index.md
  - Gromosxx: gromosxx/index.md
  - Heffte: heffte/index.md
  - Julia: julia/index.md
  - Lammps: lammps/index.md
  - Libxc: libxc/index.md
  - Linaro-forge: linaro-forge/index.md
  - Mathematica: mathematica/index.md
  - Matlab: matlab/index.md
  - Mpi4py: mpi4py/index.md
  - Namd: namd/index.md
  - Nwchem: nwchem/index.md
  - Octopus: octopus/index.md
  - Openfoam: openfoam/index.md
  - Orca: orca/index.md
  - Plumed: plumed/index.md
  - Python: python/index.md
  - Quantum-espresso: quantum-espresso/index.md
  - Rspt: rspt/index.md
  - Scalasca: scalasca/index.md
  - Score-p: score-p/index.md
  - Singularity: singularity/index.md
  - Spfft: spfft/index.md
  - Spla: spla/index.md
  - Starccm: starccm/index.md
  - Tensorflow: tensorflow/index.md
  - Uppasd: uppasd/index.md
  - Vasp: vasp/index.md
  - Veloxchem: veloxchem/index.md
  - Vmd: vmd/index.md
  - Wannier90: wannier90/index.md
