# Check that all links are valid, i.e. not broken
name: Check links

on:
  push:
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # The link checker will only work if mlc_config.json is a valid JSON
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: .github/workflows/valid_json_schema.json
          INPUT_JSONS: mlc_config.json

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'

