baseURL: "https://www.pdc.kth.se"
languageCode: "en-us"
theme: "pdc"
title: "User area"
params:
  subtitle: "PDC Center for High Performance Computing"

menu:
  main:
    - name: "PDC"
      url: "https://www.pdc.kth.se"
      weight: 1
    - name: "Support"
      url: "/support/"
      weight: 2
    - name: "Applications"
      url: "/applications"
      weight: 3
    - name: "System statistics"
      url: "/stats"
      weight: 4
    - name: "System status"
      url: "/status"
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true
relativeURLs: true
